"""
llm_service.py — LLM backend using Google Gemini API.

All heavy imports are lazy so the module is safe to import at startup
without consuming memory — models initialize on first API call only.
"""

import os
import json
import re

# ── Lazy Gemini setup ──────────────────────────────────────────────────────────
# Nothing loads at module import time. _get_model() initializes on first call.
_model = None

def _get_model():
    global _model
    if _model is None:
        import google.generativeai as genai
        key = os.getenv("GEMINI_API_KEY", "")
        if not key:
            raise RuntimeError("GEMINI_API_KEY environment variable is not set.")
        genai.configure(api_key=key)
        _model = genai.GenerativeModel("gemini-1.5-flash")
    return _model


def _gemini(prompt: str) -> str:
    """Send a single-turn prompt to Gemini and return the text response."""
    try:
        model = _get_model()
        resp = model.generate_content(prompt)
        return resp.text.strip()
    except Exception as e:
        return f"Gemini Error: {str(e)}"


# ── Presentation analysis ──────────────────────────────────────────────────────

def analyze_presentation(topic, slides, script, context,
                         ppt_warning="", audio_context="",
                         audio_metrics: dict = None,
                         has_audio: bool = False):
    """
    audio_metrics — pre-computed deterministic speech metrics.
    has_audio     — True only when the user actually recorded audio.
    """
    if audio_metrics:
        metrics_lines = []
        for k, v in audio_metrics.items():
            if k not in ("advice", "breakdown", "events", "top",
                         "uncertainty_phrases", "confidence_phrases", "audio_features"):
                metrics_lines.append(f"  {k}: {v}")
        metrics_block = (
            "--------------------------------------------------\n"
            "PRE-COMPUTED DETERMINISTIC SPEECH METRICS\n"
            "(computed from real audio signal — NOT generated by AI)\n"
            "--------------------------------------------------\n"
            + "\n".join(metrics_lines) + "\n\n"
            "IMPORTANT: These metrics are factual measurements. "
            "Ground your speech evaluation ONLY on these numbers. "
            "Do NOT invent your own scores.\n"
        )
    else:
        metrics_block = ""

    prompt = f"""
You are an elite AI viva examiner and presentation evaluator modeled after a strict university professor.

Your task is to deeply evaluate a student's presentation using ALL available sources:

1. PPT CONTENT (via RAG retrieval)
2. PRESENTATION SCRIPT (written)
{'3. AUDIO TRANSCRIPTION (spoken delivery — provided)' if has_audio else '-- No audio recording was provided for this submission --'}

You MUST combine ALL available sources together for analysis.

DO NOT analyze using only the script.
DO NOT analyze using only the PPT.
{'If audio transcription is provided, cross-check it against the script AND PPT.' if has_audio else 'IMPORTANT: The student submitted a TEXT SCRIPT ONLY — NO audio recording. Do NOT mention, reference, or evaluate audio transcription. Only evaluate the written script and PPT content.'}

You must cross-check:
- whether the script actually matches the PPT
- whether the PPT supports the script properly
- whether the student is bluffing concepts not present in PPT
- whether important PPT concepts are missing in the script
- whether the presentation structure is logically coherent

--------------------------------------------------
PRESENTATION TOPIC
--------------------------------------------------
{topic}

--------------------------------------------------
ASSIGNED SLIDES
--------------------------------------------------
{slides}

--------------------------------------------------
PRESENTATION SCRIPT
--------------------------------------------------
{script}

--------------------------------------------------
PPT CONTENT RETRIEVED USING RAG
--------------------------------------------------
{context}

{audio_context}
{metrics_block}
{ppt_warning}
--------------------------------------------------
CRITICAL EVALUATION RULES
--------------------------------------------------

1. If PPT content is weak, blank, or insufficient: explicitly mention it.
2. If PPT has only 1 slide or very few meaningful slides: mention poor quality.
3. If the script contains concepts NOT supported by PPT: mention inconsistency.
4. If the PPT contains important concepts NOT discussed in script: mention missing explanations.
5. CRITICAL DOMAIN ALIGNMENT CHECK:
   - If the PPT is about one topic and the Script is about a completely different topic, LOUDLY flag this.
   - State clearly: "The script does not align with the presentation."
6. Evaluate: technical depth, conceptual correctness, confidence, clarity, structure, topic coverage, domain knowledge.
7. Viva questions MUST use BOTH PPT concepts AND Script explanations.
8. Never hallucinate concepts not found in either PPT or script.

--------------------------------------------------
OUTPUT FORMAT — MANDATORY
--------------------------------------------------

Use EXACTLY these section headers — copy them character for character.
DO NOT write any text before the first section header.

### Presentation Analysis
[detailed analysis — paragraphs with blank lines, bullet points with -]

### Missing Concepts
[bullet points with -]

### Suggestions
[bullet points with -]

### Viva Questions
1. [question]
2. [question]
3. [question]
4. [question]
5. [question]

### Final Verdict
[2-3 sentences. Example: Score: 7/10]
"""
    return _gemini(prompt)


# ── Viva chat ──────────────────────────────────────────────────────────────────

def chat_viva(topic: str, message_history: list) -> str:
    """Multi-turn viva examiner."""
    system_prompt = (
        f"You are an elite, strict, highly experienced university professor conducting "
        f"a formal viva voce examination on the topic: '{topic}'.\n\n"
        "RULES:\n"
        "1. Challenge every surface-level answer with edge cases or real-world scenarios.\n"
        "2. Your next question MUST directly follow up on the student's previous answer.\n"
        "3. Correct mistakes aggressively and immediately.\n"
        "4. Never be overly friendly. Never use emojis.\n"
        "5. Keep responses to maximum 4 sentences.\n"
        "6. Every response MUST end with exactly one question."
    )

    history = []
    for msg in message_history:
        role = "user" if msg["role"] == "user" else "model"
        history.append({"role": role, "parts": [msg["content"]]})

    if not history:
        history = [{"role": "user", "parts": [system_prompt + "\n\nBegin the viva."]}]
    else:
        history[0]["parts"][0] = system_prompt + "\n\n" + history[0]["parts"][0]

    try:
        model = _get_model()
        chat = model.start_chat(history=history[:-1] if len(history) > 1 else [])
        last_msg = history[-1]["parts"][0] if history else "Begin."
        resp = chat.send_message(last_msg)
        return resp.text.strip()
    except Exception as e:
        return f"Gemini Error: {str(e)}"


# ── Viva evaluation ────────────────────────────────────────────────────────────

def evaluate_viva(topic: str, message_history: list) -> str:
    """Evaluate the full viva transcript. Returns JSON: { score, analysis }"""
    transcript = "\n".join(
        f"{m['role'].capitalize()}: {m['content']}"
        for m in message_history
        if m.get("role") != "system"
    )

    prompt = f"""You are an elite AI viva examiner.
You have just concluded a viva on the topic: '{topic}'.
Transcript:
{transcript}

Output ONLY valid JSON (no markdown fences, no extra text):
{{
  "score": <integer 0-100>,
  "analysis": "<2-3 paragraph evaluation string>"
}}"""

    try:
        result = _gemini(prompt)
        result = re.sub(r"```json\s*|\s*```", "", result).strip()
        json.loads(result)
        return result
    except Exception as e:
        return json.dumps({"score": 0, "analysis": f"Evaluation error: {str(e)}"})


# ── Topic auto-detection ───────────────────────────────────────────────────────

def auto_detect_topic(slides_text: str) -> str:
    """Detect the core topic from extracted PPT text."""
    if not slides_text or not slides_text.strip():
        return "Unknown Topic"

    lines = [l.strip() for l in slides_text.split("\n") if len(l.strip()) > 3]
    fallback_topic = lines[0][:60] if lines else "Unknown Topic"

    prompt = (
        "Based on the following text extracted from a presentation, identify the core academic or technical topic.\n"
        "Return ONLY the topic name (1-5 words, no punctuation, no explanation).\n\n"
        f"Extracted Text:\n{slides_text[:3000]}"
    )

    try:
        topic = _gemini(prompt)
        topic = topic.replace('"', '').replace("'", '').split('\n')[0].strip()
        topic = re.sub(
            r'^(Topic:|The topic is|Based on|The presentation is about)\s*',
            '', topic, flags=re.IGNORECASE
        ).strip()
        return topic if topic and len(topic) <= 80 else fallback_topic
    except Exception:
        return fallback_topic