"""
llm_service.py — LLM backend using Google Gemini API.

Replaces Ollama (local-only) so the backend can be deployed to any cloud host.
Model: gemini-1.5-flash (free tier: 15 req/min, 1M tokens/day)
"""

import os
import json
import re

import google.generativeai as genai

# ── Gemini setup ───────────────────────────────────────────────────────────────
_GEMINI_KEY = os.getenv("GEMINI_API_KEY", "")
if _GEMINI_KEY:
    genai.configure(api_key=_GEMINI_KEY)

_model = genai.GenerativeModel("gemini-1.5-flash")


def _gemini(prompt: str) -> str:
    """Send a single-turn prompt to Gemini and return the text response."""
    if not _GEMINI_KEY:
        return "Gemini Error: GEMINI_API_KEY environment variable is not set."
    try:
        resp = _model.generate_content(prompt)
        return resp.text.strip()
    except Exception as e:
        return f"Gemini Error: {str(e)}"


# ── Presentation analysis ──────────────────────────────────────────────────────

def analyze_presentation(topic, slides, script, context,
                         ppt_warning="", audio_context="",
                         audio_metrics: dict = None,
                         has_audio: bool = False):
    """
    audio_metrics — pre-computed deterministic speech metrics.
    has_audio     — True only when the user actually recorded audio.
    The LLM uses these for reasoning; it does NOT generate metrics itself.
    """
    if audio_metrics:
        metrics_lines = []
        for k, v in audio_metrics.items():
            if k not in ("advice", "breakdown", "events", "top",
                         "uncertainty_phrases", "confidence_phrases", "audio_features"):
                metrics_lines.append(f"  {k}: {v}")
        metrics_block = (
            "--------------------------------------------------\n"
            "PRE-COMPUTED DETERMINISTIC SPEECH METRICS\n"
            "(computed from real audio signal — NOT generated by AI)\n"
            "--------------------------------------------------\n"
            + "\n".join(metrics_lines) + "\n\n"
            "IMPORTANT: These metrics are factual measurements. "
            "Ground your speech evaluation ONLY on these numbers. "
            "Do NOT invent your own scores.\n"
        )
    else:
        metrics_block = ""

    prompt = f"""
You are an elite AI viva examiner and presentation evaluator modeled after a strict university professor.

Your task is to deeply evaluate a student's presentation using ALL available sources:

1. PPT CONTENT (via RAG retrieval)
2. PRESENTATION SCRIPT (written)
{'3. AUDIO TRANSCRIPTION (spoken delivery — provided)' if has_audio else '-- No audio recording was provided for this submission --'}

You MUST combine ALL available sources together for analysis.

DO NOT analyze using only the script.
DO NOT analyze using only the PPT.
{'If audio transcription is provided, cross-check it against the script AND PPT.' if has_audio else 'IMPORTANT: The student submitted a TEXT SCRIPT ONLY — NO audio recording. Do NOT mention, reference, or evaluate audio transcription. Do NOT write any section about audio delivery. Only evaluate the written script and PPT content.'}

You must cross-check:
- whether the script actually matches the PPT
- whether the PPT supports the script properly
- whether the student is bluffing concepts not present in PPT
- whether important PPT concepts are missing in the script
- whether the presentation structure is logically coherent

--------------------------------------------------
PRESENTATION TOPIC
--------------------------------------------------

{topic}

--------------------------------------------------
ASSIGNED SLIDES
--------------------------------------------------

{slides}

--------------------------------------------------
PRESENTATION SCRIPT
--------------------------------------------------

{script}

--------------------------------------------------
PPT CONTENT RETRIEVED USING RAG
--------------------------------------------------

{context}

{audio_context}
{metrics_block}
{ppt_warning}
--------------------------------------------------
CRITICAL EVALUATION RULES
--------------------------------------------------

You MUST STRICTLY validate the PPT itself.

1. If PPT content is weak, blank, extremely short, generic, or insufficient: explicitly mention it.
2. If PPT has only 1 slide or very few meaningful slides: mention that presentation quality is poor.
3. If the script contains concepts NOT supported by PPT: mention presentation inconsistency.
4. If the PPT contains important concepts that are NOT discussed in the script: explicitly mention missing explanations.
5. If the student heavily depends only on script quality while PPT quality is poor: mention that the presentation lacks visual/conceptual support.
6. CRITICAL DOMAIN ALIGNMENT CHECK:
   - You MUST aggressively compare the core domain/topic of the PPT against the core domain/topic of the Script.
   - If the PPT is about one topic (e.g., Compilers) and the Script is about a completely different topic (e.g., Operating Systems), you MUST loudly flag this as a critical failure.
   - Tell the student: "The script does not align with the presentation."
7. Evaluate: technical depth, conceptual correctness, confidence, clarity, structure, topic coverage, domain knowledge, practical implementation understanding.
8. Viva questions MUST be generated using BOTH PPT concepts AND Script explanations.
9. Questions must test: implementation understanding, conceptual knowledge, design decisions, edge cases, practical reasoning.
10. If PPT appears copied/generated/too generic: mention it professionally.
11. Never hallucinate concepts not found in either PPT or script.

--------------------------------------------------
OUTPUT FORMAT — MANDATORY
--------------------------------------------------

You MUST use EXACTLY these section headers — copy them character for character with no changes.
DO NOT use bold (**) for section headers.
DO NOT number or prefix the headers.
DO NOT write any text before the first section header.
DO NOT combine sections.
Separate sections with a blank line after each header.

### Presentation Analysis
[Write your detailed analysis here. Use paragraphs separated by blank lines. Use bullet points with - for lists.]

### Missing Concepts
[Use bullet points ( - ) to list missing concepts, one per line.]

### Suggestions
[Use bullet points ( - ) to list actionable improvement suggestions, one per line.]

### Viva Questions
[Write exactly 5 numbered questions — no preamble, no introduction]
1. [question]
2. [question]
3. [question]
4. [question]
5. [question]

### Final Verdict
[Write 2-3 sentences with final verdict and score out of 10. Example: Score: 7/10]

--------------------------------------------------
IMPORTANT
--------------------------------------------------

Your evaluation must feel like a strict real university viva — professional academic review with deep technical inspection.
Avoid generic motivational feedback. Avoid shallow responses. Be highly analytical.
Format your output beautifully using Markdown.
"""
    return _gemini(prompt)


# ── Viva chat ──────────────────────────────────────────────────────────────────

def chat_viva(topic: str, message_history: list) -> str:
    """
    Multi-turn viva examiner. message_history is a list of
    { role: 'user'|'assistant', content: str } dicts.
    """
    system_prompt = (
        f"You are an elite, strict, highly experienced university professor conducting "
        f"a formal viva voce examination on the topic: '{topic}'.\n\n"
        "BEHAVIORAL RULES:\n"
        "1. CHALLENGE ASSUMPTIONS: Do not just accept surface-level answers. "
        "If the student gives a textbook definition, challenge them with an edge case or a real-world scenario.\n"
        "2. ADAPT CONTEXTUALLY: Your next question MUST be a direct follow-up to the student's previous answer. "
        "Drill deeper into what they just said.\n"
        "3. CORRECT MISTAKES AGGRESSIVELY: If the student says something factually incorrect, incomplete, or vague, "
        "you MUST correct them immediately before moving on.\n"
        "4. SOCRATIC METHOD: If a student struggles, give a tiny hint, then ask them to try again.\n"
        "5. TONE: Intimidatingly smart, professional, academically formal, highly analytical. "
        "Never use emojis. Never say 'Great job!' unless truly exceptional.\n"
        "6. CONCISENESS: Keep your responses to a maximum of 4 sentences. Be direct and piercing.\n"
        "7. FLOW: Every single response you give MUST end with exactly one question."
    )

    # Build Gemini chat history
    history = []
    for msg in message_history:
        role = "user" if msg["role"] == "user" else "model"
        history.append({"role": role, "parts": [msg["content"]]})

    # Prepend system context as first user message if history is empty
    if not history:
        history = [{"role": "user", "parts": [system_prompt + "\n\nBegin the viva."]}]
    else:
        # Inject system prompt into first user message
        history[0]["parts"][0] = system_prompt + "\n\n" + history[0]["parts"][0]

    try:
        chat = _model.start_chat(history=history[:-1] if len(history) > 1 else [])
        last_msg = history[-1]["parts"][0] if history else "Begin."
        resp = chat.send_message(last_msg)
        return resp.text.strip()
    except Exception as e:
        return f"Gemini Error: {str(e)}"


# ── Viva evaluation ────────────────────────────────────────────────────────────

def evaluate_viva(topic: str, message_history: list) -> str:
    """
    Evaluate the full viva transcript and return JSON:
    { "score": int, "analysis": str }
    """
    transcript = "\n".join(
        f"{m['role'].capitalize()}: {m['content']}"
        for m in message_history
        if m.get("role") != "system"
    )

    prompt = f"""You are an elite AI viva examiner.
You have just concluded a viva on the topic: '{topic}'.
Below is the transcript of the viva session.

{transcript}

Please evaluate the student's performance based on their answers. Focus on technical correctness, clarity, and depth of knowledge shown in their responses.
You must output ONLY a valid JSON object with the following structure (no markdown fences, no extra text):
{{
  "score": <an integer between 0 and 100 representing the Viva Readiness Score>,
  "analysis": "<A detailed 2-3 paragraph string evaluating their strengths, weaknesses, and overall performance.>"
}}"""

    try:
        result = _gemini(prompt)
        # Strip any markdown code fences if model adds them
        result = re.sub(r"```json\s*|\s*```", "", result).strip()
        json.loads(result)   # validate — raises if not valid JSON
        return result
    except Exception as e:
        return json.dumps({"score": 0, "analysis": f"Evaluation error: {str(e)}"})


# ── Topic auto-detection ───────────────────────────────────────────────────────

def auto_detect_topic(slides_text: str) -> str:
    """
    Analyzes the extracted PPT text to determine the core topic.
    Returns a short string (e.g., "Compiler Design", "Distributed Systems").
    """
    if not slides_text or not slides_text.strip():
        return "Unknown Topic"

    lines = [l.strip() for l in slides_text.split("\n") if len(l.strip()) > 3]
    fallback_topic = lines[0][:60] if lines else "Unknown Topic"

    prompt = (
        "You are an AI assistant.\n"
        "Based on the following text extracted from a presentation, identify the core academic or technical topic.\n"
        "Return ONLY the topic name. Keep it concise (1 to 5 words maximum). "
        "Do not include any punctuation, explanation or conversational filler.\n"
        "If you cannot determine a topic, return the most prominent heading or term you see.\n\n"
        f"Extracted Text:\n{slides_text[:3000]}"
    )

    try:
        topic = _gemini(prompt)
        topic = topic.replace('"', '').replace("'", '').split('\n')[0].strip()
        topic = re.sub(
            r'^(Topic:|The topic is|Based on|The presentation is about)\s*',
            '', topic, flags=re.IGNORECASE
        ).strip()
        if not topic or len(topic) > 80:
            return fallback_topic
        return topic
    except Exception:
        return fallback_topic